version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  api-server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
      - TZ
      - DATABASE_URL
      - API_KEY
      - PORT
    depends_on:
      - postgres
    restart: unless-stopped
  discord-bot:
    build:
      context: ./bot
      dockerfile: dockerfile
    environment:
      - NODE_ENV=production
      - TZ
      - DATABASE_URL
      - API_KEY
      - DISCORD_BOT_TOKEN
      - DISCORD_BOT_CLIENT_ID
    depends_on:
      - postgres
    restart: unless-stopped
