FROM node:20-alpine

# copy over package.json and source code
WORKDIR /app
COPY . .

# install dependencies & build app
RUN npm ci
RUN npm run build

# set the port to expose
EXPOSE ${PORT}

# setup command to start
CMD ["npm", "start"]
